#include <ctype.h>
#include <errno.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mycc_preprocessor.h"

#define MAX_TOKENS 65536
#define MAX_PARAMS 32
#define MAX_LOCALS 256
#define MAX_FUNCS 256
#define MAX_GLOBALS 256
#define MAX_NODES 200000

typedef struct { const char *name; size_t pos; int line; int col; } Loc;
typedef enum { T_EOF, T_ID, T_NUM, T_STR, T_INT, T_RETURN, T_IF, T_ELSE, T_WHILE, T_FOR, T_VOID, T_EQ, T_NE, T_LE, T_GE, T_AND, T_OR, T_PLUSPLUS, T_MINUSMINUS, T_ARROW, T_PUNC } TokenKind;
typedef struct { TokenKind kind; long value; char text[128]; Loc loc; } Token;
typedef struct { Token *data; size_t count; size_t cap; } TokenVec;

typedef enum { N_NUM, N_VAR, N_BIN, N_ASSIGN, N_CALL, N_UNARY, N_RETURN, N_EXPR, N_BLOCK, N_IF, N_WHILE, N_DECL, N_FOR } NodeKind;
typedef struct Node Node;
struct Node { NodeKind kind; Loc loc; long value; char op; char name[64]; Node *left; Node *right; Node *third; Node **items; size_t count; };
typedef struct { Node **data; size_t count; size_t cap; } NodeVec;
typedef struct { char name[64]; int offset; } Local;
typedef struct { char name[64]; char params[MAX_PARAMS][64]; size_t param_count; Node *body; } Function;
typedef struct { char name[64]; long value; } Global;
typedef struct { const char *source; const char *file; TokenVec tokens; size_t current; NodeVec nodes; Function funcs[MAX_FUNCS]; size_t func_count; Global globals[MAX_GLOBALS]; size_t global_count; int errors; } Compiler;

static void fail(Compiler *c, Loc loc, const char *fmt, ...) {
    va_list ap; va_start(ap, fmt);
    fprintf(stderr, "%s:%d:%d: error: ", loc.name ? loc.name : c->file, loc.line, loc.col);
    vfprintf(stderr, fmt, ap); fputc('\n', stderr); va_end(ap); c->errors++;
}
static void *xcalloc(size_t n, size_t s) { void *p = calloc(n, s); if (!p) { fprintf(stderr, "mycc: out of memory\n"); exit(1); } return p; }
static void push_token(TokenVec *v, Token t) { if (v->count == v->cap) { v->cap = v->cap ? v->cap * 2 : 256; v->data = realloc(v->data, v->cap * sizeof(*v->data)); if (!v->data) exit(1); } v->data[v->count++] = t; }
static void push_node(NodeVec *v, Node *n) { if (v->count >= MAX_NODES) { fprintf(stderr, "mycc: too many syntax nodes\n"); exit(1); } if (v->count == v->cap) { v->cap = v->cap ? v->cap * 2 : 256; v->data = realloc(v->data, v->cap * sizeof(*v->data)); if (!v->data) exit(1); } v->data[v->count++] = n; }
static Node *node(Compiler *c, NodeKind kind, Loc loc) { Node *n = xcalloc(1, sizeof(*n)); n->kind = kind; n->loc = loc; push_node(&c->nodes, n); return n; }
static void add_item(Node *n, Node *item) { n->items = realloc(n->items, (n->count + 1) * sizeof(*n->items)); if (!n->items) exit(1); n->items[n->count++] = item; }

static bool word(const char *s, size_t n, const char *w) { return strlen(w) == n && strncmp(s, w, n) == 0; }
static void lex(Compiler *c) {
    const char *p = c->source; int line = 1, col = 1;
    while (*p) {
        if (*p == ' ' || *p == '\t' || *p == '\r') { p++; col++; continue; }
        if (*p == '\n') { p++; line++; col = 1; continue; }
        Loc loc = { c->file, (size_t)(p - c->source), line, col }; Token t = { T_PUNC, 0, {0}, loc };
        if (p[0] == '/' && p[1] == '/') { while (*p && *p != '\n') { p++; col++; } continue; }
        if (p[0] == '/' && p[1] == '*') { p += 2; col += 2; while (*p && !(p[0] == '*' && p[1] == '/')) { if (*p++ == '\n') { line++; col = 1; } else col++; } if (*p) { p += 2; col += 2; } continue; }
        if (isalpha((unsigned char)*p) || *p == '_') { const char *s = p; while (isalnum((unsigned char)*p) || *p == '_') { p++; col++; } size_t n = (size_t)(p - s); if (word(s,n,"int")) t.kind=T_INT; else if(word(s,n,"return"))t.kind=T_RETURN; else if(word(s,n,"if"))t.kind=T_IF; else if(word(s,n,"else"))t.kind=T_ELSE; else if(word(s,n,"while"))t.kind=T_WHILE; else if(word(s,n,"for"))t.kind=T_FOR; else if(word(s,n,"void"))t.kind=T_VOID; else { t.kind=T_ID; size_t k=n<sizeof(t.text)-1?n:sizeof(t.text)-1; memcpy(t.text,s,k); t.text[k]=0; } push_token(&c->tokens,t); continue; }
        if (isdigit((unsigned char)*p)) { char *end; errno=0; long v=strtol(p,&end,0); if(errno || end==p) { fail(c,loc,"invalid integer literal"); return; } t.kind=T_NUM; t.value=v; p=end; col+=(int)(end-(c->source+loc.pos)); push_token(&c->tokens,t); continue; }
        if (*p == '"') { p++; col++; size_t k=0; while (*p && *p!='"' && k<sizeof(t.text)-1) { if (*p=='\\' && p[1]) { p++; col++; if(*p=='n')t.text[k++]='\n'; else if(*p=='t')t.text[k++]='\t'; else t.text[k++]=*p++; col++; } else { t.text[k++]=*p++; col++; } } if(*p!='"') { fail(c,loc,"unterminated string literal"); return; } p++; col++; t.kind=T_STR; t.text[k]=0; push_token(&c->tokens,t); continue; }
        const char *two[] = {"==","!=","<=",">=","&&","||","++","--","->"}; TokenKind kinds[] = {T_EQ,T_NE,T_LE,T_GE,T_AND,T_OR,T_PLUSPLUS,T_MINUSMINUS,T_ARROW}; bool matched=false; for(size_t i=0;i<sizeof(two)/sizeof(two[0]);i++) if(p[0]==two[i][0]&&p[1]==two[i][1]) {t.kind=kinds[i];p+=2;col+=2;matched=true;break;} if(!matched) { t.kind=T_PUNC; t.text[0]=*p++; t.text[1]=0; col++; } push_token(&c->tokens,t);
    }
    Token end={T_EOF,0,{0},{c->file,(size_t)(p-c->source),line,col}}; push_token(&c->tokens,end);
}
static Token *peek(Compiler *c) { return &c->tokens.data[c->current]; }
static bool accept(Compiler *c, TokenKind k) { if(peek(c)->kind==k) { c->current++; return true; } return false; }
static bool accept_p(Compiler *c, char ch) { if(peek(c)->kind==T_PUNC && peek(c)->text[0]==ch) { c->current++; return true; } return false; }
static Token *expect(Compiler *c, TokenKind k, const char *what) { if(peek(c)->kind!=k) { fail(c,peek(c)->loc,"expected %s",what); return NULL; } return &c->tokens.data[c->current++]; }
static Token *expect_p(Compiler *c, char ch) { if(!accept_p(c,ch)) { fail(c,peek(c)->loc,"expected '%c'",ch); return NULL; } return &c->tokens.data[c->current-1]; }

static Node *expr(Compiler *c);
static Node *primary(Compiler *c) { Token *t=peek(c); if(accept(c,T_NUM)) { Node*n=node(c,N_NUM,t->loc);n->value=t->value;return n; } if(accept(c,T_ID)) { if(accept_p(c,'(')) { Node*n=node(c,N_CALL,t->loc);strncpy(n->name,t->text,sizeof(n->name)-1); if(!accept_p(c,')')) { do { add_item(n,expr(c)); } while(accept_p(c,',')); expect_p(c,')'); } return n; } Node*n=node(c,N_VAR,t->loc);strncpy(n->name,t->text,sizeof(n->name)-1);return n; } if(accept_p(c,'(')) { Node*n=expr(c);expect_p(c,')');return n; } fail(c,t->loc,"expected expression"); c->current++; return node(c,N_NUM,t->loc); }
static Node *unary(Compiler *c) { Token*t=peek(c); if(accept_p(c,'-')||accept_p(c,'!')) { Node*n=node(c,N_UNARY,t->loc);n->op=t->text[0];n->left=unary(c);return n; } return primary(c); }
static Node *mul(Compiler *c) { Node*n=unary(c); while(peek(c)->kind==T_PUNC&&(peek(c)->text[0]=='*'||peek(c)->text[0]=='/'||peek(c)->text[0]=='%')) { char op=peek(c)->text[0]; Loc l=peek(c)->loc;c->current++;Node*x=node(c,N_BIN,l);x->op=op;x->left=n;x->right=unary(c);n=x;}return n; }
static Node *add(Compiler *c) { Node*n=mul(c); while(peek(c)->kind==T_PUNC&&(peek(c)->text[0]=='+'||peek(c)->text[0]=='-')) { char op=peek(c)->text[0];Loc l=peek(c)->loc;c->current++;Node*x=node(c,N_BIN,l);x->op=op;x->left=n;x->right=mul(c);n=x;}return n; }
static Node *compare(Compiler *c) { Node*n=add(c); while(peek(c)->kind==T_EQ||peek(c)->kind==T_NE||peek(c)->kind==T_LE||peek(c)->kind==T_GE|| (peek(c)->kind==T_PUNC&&(peek(c)->text[0]=='<'||peek(c)->text[0]=='>'))) { Token*t=peek(c);char op=t->kind==T_EQ?'=':t->kind==T_NE?'!':t->kind==T_LE?'l':t->kind==T_GE?'g':t->text[0];c->current++;Node*x=node(c,N_BIN,t->loc);x->op=op;x->left=n;x->right=add(c);n=x;}return n; }
static Node *assign(Compiler *c) { Node*n=compare(c); if(accept_p(c,'=')) { Node*x=node(c,N_ASSIGN,n->loc);x->left=n;x->right=assign(c);return x;}return n; }
static Node *expr(Compiler *c) { return assign(c); }
static Node *statement(Compiler *c);
static Node *block(Compiler *c) { Token*t=peek(c);expect_p(c,'{');Node*n=node(c,N_BLOCK,t->loc);while(peek(c)->kind!=T_EOF&&!accept_p(c,'}'))add_item(n,statement(c));return n; }
static Node *statement(Compiler *c) { Token*t=peek(c); if(accept(c,T_RETURN)) {Node*n=node(c,N_RETURN,t->loc);if(!accept_p(c,';')){n->left=expr(c);expect_p(c,';');}return n;} if(accept(c,T_IF)){Node*n=node(c,N_IF,t->loc);expect_p(c,'(');n->left=expr(c);expect_p(c,')');n->right=statement(c);if(accept(c,T_ELSE))n->third=statement(c);return n;} if(accept(c,T_WHILE)){Node*n=node(c,N_WHILE,t->loc);expect_p(c,'(');n->left=expr(c);expect_p(c,')');n->right=statement(c);return n;} if(accept(c,T_FOR)){Node*n=node(c,N_FOR,t->loc);expect_p(c,'(');n->left=statement(c);n->right=expr(c);expect_p(c,';');n->third=expr(c);expect_p(c,')');add_item(n,statement(c));return n;} if(peek(c)->kind==T_INT){c->current++;Token*v=expect(c,T_ID,"identifier");Node*n=node(c,N_DECL,t->loc);if(v)strncpy(n->name,v->text,sizeof(n->name)-1);if(accept_p(c,'='))n->left=expr(c);expect_p(c,';');return n;} if(peek(c)->kind==T_PUNC&&peek(c)->text[0]=='{')return block(c);Node*n=node(c,N_EXPR,t->loc);n->left=expr(c);expect_p(c,';');return n; }
static void parse(Compiler *c) { while(peek(c)->kind!=T_EOF) { Token*t=expect(c,T_INT,"'int'"); if(!t) {c->current++;continue;} Token*n=expect(c,T_ID,"function or variable name");if(!n)continue; if(accept_p(c,'(')){Function*f=&c->funcs[c->func_count++];strncpy(f->name,n->text,sizeof(f->name)-1);if(!accept_p(c,')')){if(accept(c,T_VOID)){expect_p(c,')');}else{do{expect(c,T_INT,"'int'");Token*p=expect(c,T_ID,"parameter name");if(p&&f->param_count<MAX_PARAMS)strncpy(f->params[f->param_count++],p->text,63);}while(accept_p(c,','));expect_p(c,')');}}f->body=block(c);}else{Global*g=&c->globals[c->global_count++];strncpy(g->name,n->text,63);if(accept_p(c,'=')){Token*v=expect(c,T_NUM,"constant initializer");if(v)g->value=v->value;}expect_p(c,';');}} }

typedef struct { Compiler *compiler; char names[MAX_LOCALS][64]; size_t count; } SemanticContext;
static bool semantic_name_exists(const SemanticContext *context, const char *name) { for(size_t i=0;i<context->count;i++) if(strcmp(context->names[i],name)==0) return true; for(size_t i=0;i<context->compiler->global_count;i++) if(strcmp(context->compiler->globals[i].name,name)==0) return true; return false; }
static bool semantic_function_exists(const Compiler *compiler, const char *name) { for(size_t i=0;i<compiler->func_count;i++) if(strcmp(compiler->funcs[i].name,name)==0) return true; return false; }
static void semantic_add_local(SemanticContext *context, Node *declaration) { if(context->count>=MAX_LOCALS) { fail(context->compiler,declaration->loc,"too many local declarations"); return; } if(semantic_name_exists(context,declaration->name)) fail(context->compiler,declaration->loc,"duplicate local declaration '%s'",declaration->name); strncpy(context->names[context->count++],declaration->name,63); }
static void semantic_expr(SemanticContext *context, Node *expression) { if(!expression) return; if(expression->kind==N_VAR) { if(!semantic_name_exists(context,expression->name)) fail(context->compiler,expression->loc,"use of undeclared identifier '%s'",expression->name); return; } if(expression->kind==N_CALL) { if(!semantic_function_exists(context->compiler,expression->name)) fail(context->compiler,expression->loc,"call to undeclared function '%s'",expression->name); for(size_t i=0;i<expression->count;i++) semantic_expr(context,expression->items[i]); return; } semantic_expr(context,expression->left); semantic_expr(context,expression->right); semantic_expr(context,expression->third); }
static void semantic_statement(SemanticContext *context, Node *statement) { if(!statement) return; if(statement->kind==N_BLOCK) { for(size_t i=0;i<statement->count;i++) semantic_statement(context,statement->items[i]); return; } if(statement->kind==N_DECL) { semantic_add_local(context,statement); semantic_expr(context,statement->left); return; } if(statement->kind==N_EXPR||statement->kind==N_RETURN) { semantic_expr(context,statement->left); return; } if(statement->kind==N_FOR) { semantic_statement(context,statement->left); semantic_expr(context,statement->right); semantic_expr(context,statement->third); if(statement->count) semantic_statement(context,statement->items[0]); return; } semantic_expr(context,statement->left); semantic_statement(context,statement->right); semantic_statement(context,statement->third); }
static void semantic_check(Compiler *compiler) { for(size_t i=0;i<compiler->func_count;i++) { SemanticContext context={0}; context.compiler=compiler; for(size_t p=0;p<compiler->funcs[i].param_count;p++) { if(context.count<MAX_LOCALS) strncpy(context.names[context.count++],compiler->funcs[i].params[p],63); } semantic_statement(&context,compiler->funcs[i].body); } }

typedef struct { FILE *out; Compiler *c; Function *fn; Local locals[MAX_LOCALS]; size_t local_count; int label; } Gen;
static int local_offset(Gen*g,const char*n){for(size_t i=0;i<g->local_count;i++)if(strcmp(g->locals[i].name,n)==0)return g->locals[i].offset;return 0;}
static void emit_expr(Gen*g,Node*n);
static void emit_expr(Gen*g,Node*n){if(!n)return;switch(n->kind){case N_NUM:fprintf(g->out,"  mov $%ld, %%rax\n",n->value);break;case N_VAR:{int off=local_offset(g,n->name);if(off)fprintf(g->out,"  mov -%d(%%rbp), %%rax\n",off);else fprintf(g->out,"  mov %s(%%rip), %%rax\n",n->name);break;}case N_ASSIGN:emit_expr(g,n->right);{int off=local_offset(g,n->left->name);if(off)fprintf(g->out,"  mov %%rax, -%d(%%rbp)\n",off);else fprintf(g->out,"  mov %%rax, %s(%%rip)\n",n->left->name);}break;case N_UNARY:emit_expr(g,n->left);if(n->op=='-')fprintf(g->out,"  neg %%rax\n");else{fprintf(g->out,"  cmp $0, %%rax\n  sete %%al\n  movzb %%al, %%rax\n");}break;case N_BIN:emit_expr(g,n->right);fprintf(g->out,"  push %%rax\n");emit_expr(g,n->left);fprintf(g->out,"  pop %%rcx\n");if(n->op=='+')fprintf(g->out,"  add %%rcx, %%rax\n");else if(n->op=='-')fprintf(g->out,"  sub %%rcx, %%rax\n");else if(n->op=='*')fprintf(g->out,"  imul %%rcx, %%rax\n");else if(n->op=='/'){fprintf(g->out,"  cqo\n  idiv %%rcx\n");}else if(n->op=='%'){fprintf(g->out,"  cqo\n  idiv %%rcx\n  mov %%rdx, %%rax\n");}else{fprintf(g->out,"  cmp %%rcx, %%rax\n  %s %%al\n  movzb %%al, %%rax\n",n->op=='='?"sete":n->op=='!'?"setne":n->op=='l'?"setle":n->op=='g'?"setge":n->op=='<'?"setl":"setg");}break;case N_CALL:{static const char*regs[] = {"%rdi","%rsi","%rdx","%rcx","%r8","%r9"};for(size_t i=n->count;i>0;i--){emit_expr(g,n->items[i-1]);fprintf(g->out,"  push %%rax\n");}for(size_t i=0;i<n->count;i++){fprintf(g->out,"  pop %s\n",regs[i]);}fprintf(g->out,"  call %s\n",n->name);break;}default:break;}}
static void emit_stmt(Gen*g,Node*n){if(!n)return;switch(n->kind){case N_BLOCK:for(size_t i=0;i<n->count;i++)emit_stmt(g,n->items[i]);break;case N_RETURN:if(n->left)emit_expr(g,n->left);else fprintf(g->out,"  xor %%eax, %%eax\n");fprintf(g->out,"  jmp .Lret_%s\n",g->fn->name);break;case N_EXPR:emit_expr(g,n->left);break;case N_DECL:{if(g->local_count<MAX_LOCALS){g->local_count++;strncpy(g->locals[g->local_count-1].name,n->name,63);g->locals[g->local_count-1].offset=(int)(g->local_count*8);if(n->left){emit_expr(g,n->left);fprintf(g->out,"  mov %%rax, -%d(%%rbp)\n",g->locals[g->local_count-1].offset);}}}break;case N_IF:{int id=g->label++;emit_expr(g,n->left);fprintf(g->out,"  cmp $0, %%rax\n  je .Lelse%d\n",id);emit_stmt(g,n->right);if(n->third){fprintf(g->out,"  jmp .Lend%d\n.Lelse%d:\n",id,id);emit_stmt(g,n->third);fprintf(g->out,".Lend%d:\n",id);}else fprintf(g->out,".Lelse%d:\n",id);break;}case N_WHILE:{int id=g->label++;fprintf(g->out,".Lwhile%d:\n",id);emit_expr(g,n->left);fprintf(g->out,"  cmp $0, %%rax\n  je .Lendwhile%d\n",id);emit_stmt(g,n->right);fprintf(g->out,"  jmp .Lwhile%d\n.Lendwhile%d:\n",id,id);break;}case N_FOR:{int id=g->label++;emit_stmt(g,n->left);fprintf(g->out,".Lfor%d:\n",id);emit_expr(g,n->right);fprintf(g->out,"  cmp $0, %%rax\n  je .Lendfor%d\n",id);if(n->count)emit_stmt(g,n->items[0]);emit_expr(g,n->third);fprintf(g->out,"  jmp .Lfor%d\n.Lendfor%d:\n",id,id);break;}default:break;}}
static void generate(Compiler*c,FILE*out){char file_name[1024];size_t file_length=strlen(c->file);if(file_length>=sizeof(file_name))file_length=sizeof(file_name)-1;memcpy(file_name,c->file,file_length);file_name[file_length]='\0';for(size_t i=0;i<file_length;i++)if(file_name[i]=='\\')file_name[i]='/';for(size_t i=0;i<c->global_count;i++)fprintf(out,".data\n.globl %s\n%s:\n  .quad %ld\n",c->globals[i].name,c->globals[i].name,c->globals[i].value);fprintf(out,".text\n.file 1 \"%s\"\n",file_name);for(size_t i=0;i<c->func_count;i++){Gen g={out,c,&c->funcs[i],{{0}},0,0};fprintf(out,".loc 1 1 1\n.globl %s\n%s:\n  push %%rbp\n  mov %%rsp, %%rbp\n  sub $2048, %%rsp\n",g.fn->name,g.fn->name);static const char*regs[]={"%rdi","%rsi","%rdx","%rcx","%r8","%r9"};for(size_t p=0;p<g.fn->param_count;p++){strncpy(g.locals[g.local_count].name,g.fn->params[p],63);g.locals[g.local_count].offset=(int)((g.local_count+1)*8);fprintf(out,"  mov %s, -%d(%%rbp)\n",regs[p],g.locals[g.local_count].offset);g.local_count++;}emit_stmt(&g,g.fn->body);fprintf(out,"  xor %%eax, %%eax\n.Lret_%s:\n  leave\n  ret\n",g.fn->name);}}
static char *read_file(const char *path){FILE*f=fopen(path,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);long n=ftell(f);fseek(f,0,SEEK_SET);if(n<0||n>100000000){fclose(f);return NULL;}char*s=xcalloc((size_t)n+1,1);if(fread(s,1,(size_t)n,f)!=(size_t)n){free(s);s=NULL;}fclose(f);return s;}
static void usage(void){puts("mycc 0.1.0 - C compiler for x86-64 System V\nUsage: mycc [options] file.c\n  -E              preprocess and write source\n  -S              emit GNU assembler\n  -o FILE         output file\n  -O0..-O3        optimization level (baseline lowering)\n  --help          show this help\n  --version       show version");}
int main(int argc,char**argv){const char*input=NULL;const char*output=NULL;const char*defines[128];const char*undefines[128];const char*include_paths[128];size_t define_count=0,undefine_count=0,include_path_count=0;bool asm_mode=false;bool preprocess_mode=false;for(int i=1;i<argc;i++){if(strcmp(argv[i],"--help")==0){usage();return 0;}if(strcmp(argv[i],"--version")==0){puts("mycc 0.1.0");return 0;}if(strcmp(argv[i],"-S")==0){asm_mode=true;continue;}if(strcmp(argv[i],"-E")==0){preprocess_mode=true;continue;}if(strncmp(argv[i],"-O",2)==0)continue;if(strcmp(argv[i],"-o")==0&&i+1<argc){output=argv[++i];continue;}if(strncmp(argv[i],"-D",2)==0){const char*value=argv[i]+2;if(!*value&&i+1<argc)value=argv[++i];if(!*value||define_count==128){fprintf(stderr,"mycc: invalid -D option\n");return 2;}defines[define_count++]=value;continue;}if(strncmp(argv[i],"-U",2)==0){const char*value=argv[i]+2;if(!*value&&i+1<argc)value=argv[++i];if(!*value||undefine_count==128){fprintf(stderr,"mycc: invalid -U option\n");return 2;}undefines[undefine_count++]=value;continue;}if(strncmp(argv[i],"-I",2)==0){const char*value=argv[i]+2;if(!*value&&i+1<argc)value=argv[++i];if(!*value||include_path_count==128){fprintf(stderr,"mycc: invalid -I option\n");return 2;}include_paths[include_path_count++]=value;continue;}if(argv[i][0]=='-'){fprintf(stderr,"mycc: unknown option %s\n",argv[i]);return 2;}input=argv[i];}if(!input){usage();return 2;}char*source=read_file(input);if(!source){fprintf(stderr,"mycc: cannot read %s\n",input);return 1;}MyccPreprocessorOptions preprocessor_options={defines,define_count,undefines,undefine_count,include_paths,include_path_count};int preprocessing_errors=0;char*preprocessed=mycc_preprocess_with_options(source,input,&preprocessor_options,&preprocessing_errors);free(source);if(!preprocessed||preprocessing_errors){free(preprocessed);return 1;}source=preprocessed;if(preprocess_mode){FILE*out=stdout;if(output){out=fopen(output,"w");if(!out){fprintf(stderr,"mycc: cannot write %s\n",output);free(source);return 1;}}fputs(source,out);if(out!=stdout)fclose(out);free(source);return 0;}Compiler c={0};c.source=source;c.file=input;lex(&c);parse(&c);if(c.errors){free(source);return 1;}semantic_check(&c);if(c.errors){free(source);return 1;}FILE*out=stdout;if(output){out=fopen(output,"w");if(!out){fprintf(stderr,"mycc: cannot write %s\n",output);free(source);return 1;}}else if(!asm_mode){fprintf(stderr,"mycc: executable/object generation requires -S in this release\n");free(source);return 2;}generate(&c,out);if(out!=stdout)fclose(out);free(source);for(size_t i=0;i<c.nodes.count;i++){free(c.nodes.data[i]->items);free(c.nodes.data[i]);}free(c.nodes.data);free(c.tokens.data);return 0;}
